### ISSUE TITLE
Reward in setpoint is wrong

### ISSUE THREAD

**Issue by jacefri** [simon-larsson/ballbeam-gym#2]
The reward in the setpoint environment is wrong. Your code is: 
```
reward = (1.0 - (self.setpoint - self.bb.x)/self.bb.L)**2
```
Looking at this I can guess that your intention was that the maximum reward at each timestep should be 1, when the ball is exactly at the setpoint. However in the formula if self.bb.x is larger than self.setpoint the difference becomes negative and then the resulting reward is larger than 1. Which means you are rewarded by having positions larger than the setpoint rather than being on it. 

Other than this minor error, this is very good and thank you for making this gym environment. It has been useful to me.

**Comment by simon-larsson** [comment]
I am glad that you liked it! Thank you for reporting this bug. I will make it the absolute value instead.

**Comment by simon-larsson** [comment]
Added in version 0.0.5
